version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: &app app
    platform: linux/amd64
    container_name: go-boilerplate-api
    ports:
      - "3000:3000"
    env_file:
      &envfile
      - .env
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
    command: >
      sh -c "CompileDaemon --build=\"go build main.go\" --command=./main"
    depends_on:
      - db
      - redis
    networks:
      - default

  redis:
    restart: always
    platform: linux/amd64
    image: redis:latest
    ports:
      - "6392:6379"

  db:
    image: postgres:12-alpine
    platform: linux/amd64
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5440:5432

  worker-send-otp:
    build:
      context: .
      dockerfile: worker.Dockerfile
    image: *app
    platform: linux/amd64
    restart: always
    env_file: *envfile
    environment:
      - IS_APP_SERVER=false
      - QUEUE_NAME=prod-send-otp
    command:
      [
        "go",
        "run",
        "main.go"
      ]
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    networks:
      - default

  worker-send-email:
    build:
      context: .
      dockerfile: worker.Dockerfile
    image: *app
    platform: linux/amd64
    restart: always
    env_file: *envfile
    environment:
      - IS_APP_SERVER=false
      - QUEUE_NAME=prod-send-email
    command:
      [
        "go",
        "run",
        "main.go"
      ]
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    networks:
      - default
